#!/bin/sh

set -e # Exit on any failure


# loads git completion script if necessary.
if ! [ -f ./.git-completion.bash ]; then
  curl --silent https://raw.githubusercontent.com/git/git/5c38a1fad748696108339c74f741e1a8a3ea79a2/contrib/completion/git-completion.bash -o ./.git-completion.bash
fi

# creates .gitconfig.temp
touch ./.gitconfig.temp
cat ./.gitconfig > ./.gitconfig.temp
cat ./.gitconfig-user >> ./.gitconfig.temp

cp .bash_profile        $HOME/.bash_profile
cp .gitconfig.temp      $HOME/.gitconfig
cp .gitignore_global    $HOME/.gitignore_global
cp .irbrc               $HOME/.irbrc
cp .rspec               $HOME/.rspec
cp .inputrc             $HOME/.inputrc
cp .vimrc               $HOME/.vimrc
cp .git-completion.bash $HOME/.git-completion.bash

test -d /Applications/Sublime\ Text\ 2.app/ && {
  cp Prefrences.sublime-settings-user $HOME/Library/Application\ Support/Sublime\ Text\ 2/Packages/User/Preferences.sublime-settings
  cp sublime_key_bindings $HOME/Library/Application\ Support/Sublime\ Text\ 2/Packages/User/Default\ \(OSX\).sublime-keymap
}

test -d /Applications/Sublime\ Text.app && {
  echo "Sublime Text 3 prefs auto install not currently supported."
}

curl --silent http://levien.com/type/myfonts/Inconsolata.otf -o $HOME/Library/Fonts/Inconsolata.otf

./sublimelink
