#!/bin/sh

set -e # Exit on any failure


# loads git completion script if necessary.
if ! [ -f ./.git-completion.bash ]; then
  curl --silent https://raw.githubusercontent.com/git/git/5c38a1fad748696108339c74f741e1a8a3ea79a2/contrib/completion/git-completion.bash -o ./.git-completion.bash
fi

# adds user info to gitconfig
cat ./.gitconfig       > ./.gitconfig.temp
cat ./.gitconfig-user >> ./.gitconfig.temp

# adds secrets to .bash_profile
cat ./.bash_profile  > ./.bash_profile.temp
cat ./.secrets      >> ./.bash_profile.temp

cp .bash_profile.temp   $HOME/.bash_profile
cp .gitconfig.temp      $HOME/.gitconfig
cp .gitignore_global    $HOME/.gitignore_global
cp .irbrc               $HOME/.irbrc
cp .rspec               $HOME/.rspec
cp .inputrc             $HOME/.inputrc
cp .vimrc               $HOME/.vimrc
cp .gemrc               $HOME/.gemrc
cp .git-completion.bash $HOME/.git-completion.bash

test -d /Applications/Sublime\ Text\ 2.app/ && {
  cp Prefrences.sublime-settings-user $HOME/Library/Application\ Support/Sublime\ Text\ 2/Packages/User/Preferences.sublime-settings
}

# prevents changes to /.gitconfig-user from being tracked.
git update-index --skip-worktree ./.gitconfig-user

./sublimelink
